[google_service_account]
type = "service_account"
project_id = "plenary-network-437301-u4"
private_key_id = "aad504a3b86150ac274bbb4d17e1cabd8cb4de6b"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCk5Qr8hnS20On5
kobA1zKhyAoJoxmebLEZJPM9xCI3TYRPXXg9AZSY03VF34hATo5WTIPnjMazE9U1
4eOg6+pLiiS5HQf0pLx97Bp2j4Xx4gbCXq6Cl2gvlSfUj9uLAYjixp0Qwx2BilsO
M5iH0V0vU+0jVFbUEAtK2p2A5LYiimqCB1f6SVZnpb3vwXWtE4XMKiRfijsgSTsn
KMebxbJmYTLHeopXt2ybKqRiSJjjqZacA7h/ewNPLFaixVa3jfkosOhl1uXn/0z5
7p1Rmc1mfKJcTlNxze5zodm/MEjwxF5J6rlbq8q3qA9aDUaLYXygfL89TLwfPTS4
80eQTdSpAgMBAAECggEAAMXExUiFJbbzxQGaxsQYq+wdtZbuvOtQsZfWxBEbYW5d
f93bMpBONPXsUzCwHlqtMp+OuyVxqAoK33hLVRgh26soz01g5F8nYGt8TMD7oqBZ
gdczIrATqCxpreaOI7gKPy4TyI3cy/wc/4N+ST2cfdx7FxAojNC17X/5yVkDoZoJ
5pE5gvcf5uoYh8poXWaAuqm5UwqMsLByTD7AAV7M2D3uAbGR5yoo8/lciyDRmY39
qH2+C3HVSK0NlK2dq1j+Ib+9sAUwBOe1cCnS/xG5CcSkWBqqQlzbvQ7Vv1P6mdVv
22qrJ+xiy5DqmOaGWP9a4fSSnLzx+ynrIGTJy8+58QKBgQDYxzNGwaG360yS+CI1
fyEkKb0M8bSAOrSI/Lch/vxeZOAddxPhy6gwN0lcJl5QJTveUwpiblVkNBo+6Pdu
TXqwRtgF29qj+fnuFt9OJubGnkmumLLeYUO88488Bc7+qxxR6ERqNquDCSznSQi8
uHt/F/7Qa0Q/6j9N7fPi13baeQKBgQDCurBteL2vedBoPUIWROqGvNVAwdZe8vIx
QlcJHLAi0EHSnUlcg4fKS8k6NSbI+JPTd4Ej4qCneHL6LXbEjudbBgN1sFaeVKln
v4Km+Xapr6Bk6nlIXZl/s1t9UI3Z+Xl5+DoIedYY0onjm36MGRzpBVm2SEZ8vdAL
tGIj6wU/sQKBgFA7af8GK5SmwfCjZgXmx51a1V21F9ld4PPSlPVAKqfFLi25pOIt
PlKaI8y3ZrDDFyVyFqXXsEMmBZDDKNDqXD5h+hIxDPsjyh0U2hFS1JcufpbgbVNh
LHECtEDC5ZncOt8V2Dx3f4NAIh54KYOvxAWGHAmHqfr99/Af4eRTWuoBAoGAcD8O
zbuIk6rDACM3ggCts4cL4e0Z9ddS1iQoaV85BIhJOO9jR0mmL2zqDHxw4+2twHql
XRsYghCDLkSgroK1R5m6ys8fztp8YApbdIZd6UgMS7+As78IaTzo4t5ZNimA5Va5
lQMt71cFFscd9gHP0V49LT6SKvt6/hQ3cf7aIrECgYAG+fM6sa4dUAQa+UcmdExg
yH51cL2FDnwVUxwN3fEdeIIdb5kxK4w01kvG2CwFtSj2ExuDIjnnVZ20TndwCIFG
F9bUmUa+LumgkzMOZUuyKDzYqMX8vkPUhBNq7olwY2hliiouUmSzP1ri+pT/E7pm
tYgOvFzlQj+QQYKwQeH0Kw==
-----END PRIVATE KEY-----"""
client_email = "phide-fraternos@plenary-network-437301-u4.iam.gserviceaccount.com"
client_id = "105559871037938289972"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/phide-fraternos%40plenary-network-437301-u4.iam.gserviceaccount.com"
universe_domain = "googleapis.com"