[google_service_account]
type = "service_account"
project_id = "plenary-network-437301-u4"
private_key_id = "6a2eec17210d9edaad95d4fe4d2496e3ae2bfdb2"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCl/S8LyLb65dSW
XG/740VqFpKpOIxIMu7H8p/WLhei+iLyFQ2oEKgfBcKeJl0VIma3SEvru+ZetY7b
y6zxzspxFhKA/rHr9+4au0U36fsiH+vrlftw+qMfoP4A2zSKWZqq8l25PSgHeFhr
Ra5ayYFBnQcUpkuGnKYQW2ThOOPJv7tqdjmxQ8uipXgcAAjYeyLmmDEHKfltO1Fl
zPVlu8eecPo/sA0qQ3LM+mUkJYcpkV6JuDFKyRDKMdrOJZgyFmnt51tLQvnW4RFz
ZS2uGpjnj3BCGZifb116xJmegKYf7Rua99h9zWy9p/LXKJvBx7EpHWh6OE6W3PIP
NUTlaKIhAgMBAAECggEAA/7TppN2wBRPKS1hbq06SwLvFc6sJcLAF6UB7uxeGkiu
FainEwAPo+uGEzt2Kx+QXGILncmAkpAJN8YvzAQ/wDgZSuyWiMkHfLI8SMvDhT9C
dQG/syj9SzIbWxbrrVbZz7qUwfQ0ZfWiHzbmqv3FtDgc5wTXtY5IuwUQKRGu/fir
FBl5SQTnfY+DQlWKHrzjFx92YNVV1bsMBEHEInCUqjz0LbWWx0IgbV1XrgPSP4cg
D7Ggqw7pEeGXeh0Wg5rl9FY79IkMqlLSyZ1qA8N61u90ExSzN+hxbJMT/+Po9Dj3
yxfIrrj0OPeXmIMz+KRe3PIccId0BS1LYiw/ajcE/wKBgQDQEXTNnA6WJSldpCLf
rGRtw+KRfoxAuteO4Lz1Sj92OlmIi0LdVoS65UmozqEQNnaeUc+tLJJi6vEYTX1k
bNnQU8HtwBm1QwEo/kPDKbD+e14nhAxd9Z6ZCJp8652MifD73FGAApX8LR2zv5Q5
VoM7GHqSnF5LoohOQ19XUUtpewKBgQDMOinZYYfj3jRSpIYvYASPUn40ItSgbMoz
aza46crYcGfeU4AtAxDNkjSAZNpZrqRaApFkmuokc/VSVRLhyWOeg3osQzA2pFkd
XxvL248S2YXpo7eobf0EOE+Bj+4USkr9kxCDunwDR8ldLa7CBz8GHsJBb9d8+Cyg
oxThFsMKEwKBgC2/yNj0uVhWL3RBhNF9jE9+RLENDDWnX4Iw9BtTCgUq60jUpg0Y
2vJlO/77//oan5ZMEsfXBxDs67oWP733GSVvZTKrjHuIkha7YZbl8d7irV8u77Ex
MoAfnihdfjTKl8wpM1pcNzJNkTxWoXbCCPTTexAFhc5HnITo12vRmi1FAoGAGTED
gID7VixOn/MTajyZ02QFlUDGoZNJzdXnxh9wmgojhdUe9m5uYC0stLm8BVv5gfDX
JmXFhAGZvTIpRhilZSQqqdMP222iYHEe6KKIn3adghhjyy7mCuM3S3AJmg8f+O9v
FhCmw3DTcd70s5JZP9QDejblidDDEH2NUcaRAGkCgYEAmkZFJIPliOkzwZVi0e9w
sEcuFSQ/h7ihx13YOCK3ZIsCDOyvPPbL/J1hbNKWlERK1opQK+fMVqcMfqP4TVRz
kmJor4vccRWqPzGml2lp5xWheLwUFiTqONugg4uA2qT6tGGN7crbeo5Sec5T2wDh
hxx+We5CUEYMqfT3nafHz14=
-----END PRIVATE KEY-----\n"""
client_email = "phide-fraternos@plenary-network-437301-u4.iam.gserviceaccount.com"
client_id = "105559871037938289972"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/phide-fraternos%40plenary-network-437301-u4.iam.gserviceaccount.com"